Run lints/test even when others fail (testing failure)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,15 +27,26 @@ jobs:
       with:
         python-version: ${{ matrix.python-version }}
     - name: Install dependencies
+      id: install-deps
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
         pip install -r requirements-dev.txt
-    - name: Lint
+    - name: Check formatting
+      # Lints/tests should always run, even if other lints/tests have failed.
+      if: success() || failure() && steps.install-deps.outcome == "success"
       run: |
         black --check .
+        exit 1  # FIXME: Temp failure to check that future steps run.
+    - name: Lint
+      if: success() || failure() && steps.install-deps.outcome == "success"
+      run: |
         ruff .
+    - name: Check types
+      if: success() || failure() && steps.install-deps.outcome == "success"
+      run: |
         mypy
     - name: Run tests
+      if: success() || failure() && steps.install-deps.outcome == "success"
       run: |
         pytest -vv
